export const FETCH_FILM_DATA = 'FETCH_FILM_DATA';
export const FETCH_FILM_DATA_SUCCEEDED = 'FETCH_FILM_DATA_SUCCEEDED';
export const FETCH_FILM_DATA_FAILED = 'FETCH_FILM_DATA_FAILED';
export const FETCH_PERSON_DATA = 'FETCH_PERSON_DATA';
export const FETCH_PERSON_DATA_SUCCEEDED= "FETCH_PERSON_DATA_SUCCEEDED";
export const FETCH_PERSON_DATA_FAILED = "FETCH_PERSON_DATA_FAILED";